### ISSUE TITLE
Game of Life importing RLE patterns

### ISSUE THREAD

**Issue by PaszaVonPomiot** [RoboUlbricht/arduinoslovakia#1]
Hey,

Great job with Game of Life on Arduino. I run it on UNO in HW mode and works very well. How do you think it could be possible to import patterns in RLE format from following site?
[http://www.conwaylife.com/wiki/Category:Patterns](http://www.conwaylife.com/wiki/Category:Patterns)

**Comment by RoboUlbricht** [comment]
Interesting site. RLE format seems to be not very complicated.

**Comment by RoboUlbricht** [comment]
Ad acta.
