### ISSUE TITLE
[Question] Looking for example SPIFFS, ESP8266, HTML-Template

### ISSUE THREAD

**Issue by chess-levin** [RoboUlbricht/arduinoslovakia#2]
Hi, I've just found your ESP8266WebServer with SPIFF demo. That helped me a lot!!! Thank you!

I'm wondering if you could recommend a best practice for the following task:

I want to use ESP8266WebServer to show some sensor readings on a web page. So the most part of the webpage is static code. There are only a few places where I want to use a variable. Do you no how to use a HTML-Template (stored as SPIFF) and replace the variable with my current sensor value, just before sending the HTML-reponse.
Thank you in advance!

**Comment by RayOS9** [comment]
Did you found how to solve it@ @chess-levin ?

**Comment by chess-levin** [comment]
As I want to stick to ESP8266WebServer I found no good example. There are some examples of a TemplateProcessor based on ESPAsyncWebServer, e.g search for processor in https://embedgyan.wordpress.com/2022/02/12/create-a-wi-fi-manager-asyncwebserver-library-with-esp8266-nodemcu/
